url: http://timjbaer.github.io
baseurl: ""

# Site Settings
title: Tim Baer
description: "Tim Baer Homepage"
keywords: "Tim Baer, Numerical Linear Algebra, Graph, Tensor, LPNA, Illinois"
collections:
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown
highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]
